- concordium_p2p_rpc.proto
The node will support a set of connections that are not part of the normal "randomly drop" routine. This adds support for managing those connections in a running node.
> Add endpoint for disconnecting a peer.

- concordium_p2p_rpc.proto
The Javascript proto generator translates a uint64 to a number, but a number cannot safely represent 64 bit integers. This change will make sure that the tool translate uint64 to string instead, which will enable us to map the data types correctly.
Added Javascript type annotations to the proto file.
> Add JS annotations to map uint64 to string

- concordium_p2p_rpc.proto
This adds the possibility of specifying a base genesis index when calling `GetBlocksByHeight`. The height is treated as relative to this index. It is also possible to restrict the query to the specified genesis index.
Add the fields `from_genesis_index` and `restrict_to_genesis_index` to the `BlockHeight` message type. (As we are using proto3, these are automatically optional, and default to 0 and false, respectively. This means that if they are not provided the height will be treated as an absolute height.)
> Support block height query relative to a genesis index

- google/protobuf/wrappers.proto
Newer tools (tonic 0.8) to not seem to have this file hard-coded so we need to
add it as a dependency.
Supports builds with more recent version of code generation tools.
Add `wrappers.proto`, the standard google wrappers for common types.
> Add common types to the repo.

- v2/concordium/service.proto
- v2/concordium/types.proto
Implement some of the new gRPC api v2 functions. https://github.com/Concordium/concordium-node/issues/433
Should be merged with https://github.com/Concordium/concordium-node/pull/482
- Extend the gRPC api v2 service with `GetModuleList`, `GetModuleSource`, `GetInstanceList`, `GetInstanceInfo`, `GetNextAccountSequenceNumber`, `GetConsensusInfo`, `GetAncestors` and some initial work for `GetTransactionStatus`.
- Added the relevant types.
- Introduce `AccountIdentifierInput` and updated `AccountInfoRequest` to use it.
> First round of gRPC api v2 functions

- v2/concordium/service.proto
- v2/concordium/types.proto
Adding more functions to gRPC v2 API.
Related to https://github.com/Concordium/concordium-node/pull/494.
- Extend gRPC api v2 with `GetCryptographicParameters`, `GetBlockInfo`, `GetBakerList`, `GetPoolStatus`, `GetPassiveDelegationStatus`, `GetBlocksAtHeight` and `GetTokenomicsStatus`.
- Renamed `BlockInfo` type used in `GetBlocks` to `ArrivedBlockInfo`.
> Another round of gRPC v2 api functions

- v2/concordium/service.proto
- v2/concordium/types.proto
Add getter functions for delegators and for branches in v2.
Related to https://github.com/Concordium/concordium-node/pull/513 and https://github.com/Concordium/concordium-rust-sdk/pull/43
- Add `GetPoolDelegators`, `GetPoolDelegatorsRewardPeriod`, `GetPassiveDelegators`, `GetPassiveDelegatorsRewardPeriod` and `GetBranches`.
> Add getters for delegators and branches in v2

- v2/concordium/service.proto
- v2/concordium/types.proto
Implement more of API v2.
Related issue https://github.com/Concordium/concordium-node/issues/433.
Should be merged with https://github.com/Concordium/concordium-node/pull/521.
- `GetElectionInfo`, `GetIdentityProvidersV2`, `GetAnonymityRevokers` and `GetAccountNonFinalizedTransactions`.
> API v2 Getters for info about election, IP, AR and nonfinal tx

- v2/concordium/types.proto
Introduce the new reject reasons related to SC upgrading.
Added the following types to the set of possible reject reasons. 
- UpgradeInvalidModuleReference
The contract upgrade failed because of an invalid module reference
- UpgradeInvalidContractName
The contract upgrade failed because the new module did not have a corresponding contract name.
- UpgradeInvalidVersion
The contract upgrade failed because the new module does not support contract upgrades.
> Support for smart contract upgrades.

- v2/concordium/types.proto
Basic support for the P6 variant. 
Addresses: https://github.com/Concordium/concordium-node/issues/636
Added a P6 to the protocol version enum.
> Basic support for P6

- v2/concordium/types.proto
Support the new chain parameters in the GRPC API V2
New type definitions for types related to the new consensus. (P6)
- `ChainParametersV2`
- `ConsensusParametersV1`
- `TimeoutParamters`
- timeout base
- timeout increase
- timeout decrease
- `MinBlockTime`
- `BlockEnergyLimit`
- `GasRewardsCpv2` (Does not support `finalization_proof` reward)
Changes to existing types: 
- The access structure for `parameter_election_difficulty` has been renamed to `parameter_consensus` as it will be the same set of keys that can change this properties of the chain.
> Chain parameters v2

- CHANGELOG.md
- v2/concordium/types.proto
Related to https://github.com/Concordium/concordium-node/issues/837
Should be merged with https://github.com/Concordium/concordium-base/pull/374 and https://github.com/Concordium/concordium-node/pull/838
- Add changelog for API v2.
- Provide the protocol version of the block in `GetBlockInfo`.
- Expand `BlockHashInput` to also take relative and absolute block height.
> Query by block height directly

- CHANGELOG.md
- v2/concordium/types.proto
To make the appropriate changes to the proto file in order to solve https://github.com/Concordium/concordium-node/issues/870. 
Changes to the `ConsensusInfo` message type:
* `slot_duration` is now optional
* optional fields `current_timeout_duration`, `current_round`, `current_epoch`, `trigger_block_time` are added
Changes to the `BlockInfo` message type:
* `slot_number` is now optional
* optional fields `round` and `epoch` are added
Changes to the `ElectionInfo` message type:
* `election_difficulty` is now optional
> Fix dummy grpc values

- CHANGELOG.md
- v2/concordium/service.proto
- v2/concordium/types.proto
Introduced the endpoint and types required to support `GetBlockCertificates`.
> Support for `GetBlockCertificates`

- CHANGELOG.md
- v2/concordium/types.proto
Add the commission rates for the current reward period to `PoolCurrentPaydayInfo`.
> Add commission rates to `PoolCurrentPaydayInfo`

- CHANGELOG.md
- v2/concordium/types.proto
It seems that the `UpdateInstructionSignature` and `AccountTransactionSignature` was meant to replace the `SignatureMap`. However it also seems that the `UpdateInstructionHeader` was never updated to include the `UpdateInstructionSignature` as intended.
Since the `SignatureMap` is only used in the `UpdateInstructionHeader` I propose to remove `UpdateInstructionHeader` and move the comments to `SignatureMap`. This should of course be a non-breaking change.
> Remove `UpdateInstructionSignature`

- CHANGELOG.md
- grpc/health/v1/health.proto
- v2/concordium/health.proto
Add a new health check endpoint that fits to Google's requirement https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto
> Add canonical grpc health check service.

- CHANGELOG.md
- v2/concordium/types.proto
Prepare the API for protocol version 7 as part of https://github.com/Concordium/concordium-node/issues/1066.
See also https://github.com/Concordium/concordium-base/pull/474 and https://github.com/Concordium/concordium-node/pull/1075.
> Add protocol version 7

- CHANGELOG.md
- v2/concordium/types.proto
Revise API to support changes to cooldowns in protocol version 7.
- `AccountInfo` has a new repeated `cooldowns` field. Each `Cooldown` records the amount, (expected) release time and whether it's a regular cooldown, pre-cooldown or pre-pre-cooldown.
- `AccountInfo` now includes `available_balance`. This is included since the method for calculating it has changed (it now must account for the cooldowns), so this is provided as a convenience.
- `PoolInfoResponse` is revised to make the fields `equity_capital`, `delegated_capital`, `delegated_capital_cap` and `pool_info` optional. This is since in protocol 7 a validator can be unregistered, but still part of the current epoch validators.
> API support for cooldown changes

- v2/concordium/types.proto
This adds the new protocol version 8 to the protobuf types.
Protocol version 8 will incorporate the suspension of inactive validators proposal.
A new protocol version is added to the protobuf definitions.
> NOD598: Add new protocol version to proto types

- v2/concordium/types.proto
We add the `is_suspended` flag to the grpc representation of `AccountInfo`. This is a new flag indicating whether an account is currently suspended or not and is introduced in protocol 8.
> protocol 8: New `is_suspended` flag for `AccountInfo`

- v2/concordium/types.proto
Clearly, the is_suspended flag will always be set to false for all protocol versions < 8.
> docs: fixed wrong comment

- v2/concordium/types.proto
This adds suspend/resume transaction types for validators to self-suspend or resume.
> suspended validators: Add suspend/resume tx types

- CHANGELOG.md
- v2/concordium/types.proto
The changes to cooldown behaviour now allow an account to transition directly from delegator to baker and vice-versa. In these cases, an additional event is generated in the configure baker/delegator transaction to indicate that the delegator/baker has been removed.
- Add `delegation_removed` and `baker_removed` events to `BakerEvent` and `DelegationEvent` respectively.
> Add missing events for baker/delegator configure transactions

- v2/concordium/service.proto
- v2/concordium/types.proto
Minor cleanup of doc comments, needed to fix some warnings for the generated code in C# SDK.
> Remove trailing whitespace and extra `/` for comments

- v2/concordium/types.proto
This moves the suspended flag from `AccountInfo` to `AccountStakingInfo.Baker`.
Reflect that the the suspended flag is associated to validators, not the account.
see above.
> p8: move suspended flag

- CHANGELOG.md
- v2/concordium/service.proto
- v2/concordium/types.proto
New GRPC endpoint for getting detailed consensus status in consensus version 1.
- Add new types.
- Add new endpoint.
> Support consensus detailed status

- CHANGELOG.md
- v2/concordium/service.proto
- v2/concordium/types.proto
Issue: https://github.com/Concordium/concordium-node/issues/1263
Related: https://github.com/Concordium/concordium-base/pull/575 https://github.com/Concordium/concordium-node/pull/1260
Add gRPC endpoints for getting the lists of accounts with scheduled releases or cooldowns.
- GetScheduledReleaseAccounts endpoint
- GetCooldownAccounts endpoint
- GetPreCooldownAccounts endpoint
- GetPrePreCooldownAccounts endpoint
> Queries for getting which accounts have scheduled releases or cooldowns.

- CHANGELOG.md
- v2/concordium/types.proto
Add chain parameters version 3 to the definitions, containing the new `ValidatorsScoreParameters` parameters.
See above.
> Add chain parameters v3

- v2/concordium/types.proto
Extend the `SpecialTransactionOutcome` message with a `ValidatorSuspended` message.  Needs to be merged after the new chain parameters, https://github.com/Concordium/concordium-grpc-api/pull/66.
see above.
> Add new special transaction outcome

- v2/concordium/types.proto
We add the account address of the suspended/primed validator to the special events. This is needed for tooling.
See above.
> Added account address to ValidatorSuspended/PrimedForSuspension

- CHANGELOG.md
- v2/concordium/types.proto
Add suspension info to `PoolInfo` /  `PoolCurrentPaydayInfo`.
See above.
> Suspend info in `PoolInfoResponse` and `PoolCurrentPaydayInfo`

- v2/concordium/types.proto
Relates to: https://github.com/Concordium/concordium-node/issues/1309
Clarify when `is_suspended` may be absent.
> Clarify when `is_suspended` may be absent.

- CHANGELOG.md
- v2/concordium/kernel.proto
- v2/concordium/protocol-level-tokens.proto
- v2/concordium/service.proto
- v2/concordium/types.proto
Define protobuf message types for:
- Token account/block level state
- Token identifiers
- Token events for token operations (transfer, mint, burn)
Extend `AccountInfo` structure to incorporate token state (balance, allow/deny list), enabling token support within existing account framework.
Mermaid diagrams of the current design proposal:
`types.proto`: https://gist.github.com/drsk0/388bef8640220d54a479d3f39eb52599
`protocol-level-tokens.proto`: https://gist.github.com/drsk0/80f8fd34509b3f9cc046e9e028f5b1ed
`kernel.proto`: https://gist.github.com/drsk0/77e3e4787f3383083485721d5a3e2f63
`services.proto`: https://gist.github.com/drsk0/c352e07a55093adfaa51de8b137644db …
> plt: Implement token data structures and account integration

- v2/concordium/types.proto
Closes https://linear.app/concordium/issue/CCD-240/update-grpc-documentation
Improvements to the grpc documentation with respect to the audience of an `event` consumer 
e.g. someone writing an indexer that looks up some events to figure out:
- What causes the event (e.g. chain/protocol event or is it related to a transaction type)?
- Does the event occur in tandem with other events?
- Are there similar events (that could cause confusion e.g. similar naming) that people should be aware of?
- Did any protocol version added, removed, changed the event/type/message?
I focused mainly on `baker/delegator events` and `reward events` for now.
- Add documentation regarding `capital/leverage` bounds.
- Expose formula used for the `delegate_stake_cap` calculation.
- Clarifications of baker/delegator …
> Update grpc documentation

- CHANGELOG.md
- v2/concordium/types.proto
Part of COR-683
Required by https://github.com/Concordium/concordium-base/pull/627
Required by https://github.com/Concordium/concordium-node/pull/1379
Add a reject reason for PLT token holder transactions.
- Add reject reason.
> Add `token_holder_transaction_failed` `RejectReason`.

- CHANGELOG.md
- v2/concordium/types.proto
Support for token governance transactions (ref COR-688)
Related PR for base https://github.com/Concordium/concordium-base/pull/622
Related PR for node: https://github.com/Concordium/concordium-node/pull/1371
- Extend with transaction type variant for `TokenGovernance` transactions.
- Introduce reject reason representing: Unauthorized for token governance.
> Add token governance transaction type and reject reason
