Concordium/concordium-grpc-api

concordium_p2p_rpc.proto
To remove the staging_net feature as per https://github.com/Concordium/concordium-node/issues/71
Removed the staging_net username from the protobuf. 
=> Removed staging net feature.

concordium_p2p_rpc.proto
Add a new entrypoint to invoke a smart contract locally on the node and return the result of execution.
Add a new RPC call.
=> Add invoke contract entrypoint.

concordium_p2p_rpc.proto
Add new endpoints to support delegation changes.
=> Delegation

v2/concordium/service.proto, v2/concordium/types.proto
This is part of the GRPC2 revision and contains the initial setup and types required for the
- GetAccountInfo
- GetFinalizedBlocks
- GetBlocks
- GetAccountList
endpoints.
- add v2 type description and service description files.
=> Start grpc2 revision.

v2/concordium/service.proto, v2/concordium/types.proto
Add an endpoint to retrieve the entire contract state. This was a feature that was requested by users and it makes good sense.
=> Add a streaming contract state endpoint.

v2/concordium/service.proto, v2/concordium/types.proto
Peers info endpoint for grpc2 API
Introduced the new types `PeersInfo`  et. al. together with the endpoint. 
=> peers info

v2/concordium/service.proto, v2/concordium/types.proto
API for starting and stopping network dumps on the node. 
_Describe the changes that were needed.
=> grpc2 network dumps 

v2/concordium/service.proto, v2/concordium/types.proto
Banning functionality for the new grpc api. 
_Describe the changes that were needed.
=> GRPC2 - Banning

v2/concordium/service.proto, v2/concordium/types.proto
Expose `peer` connect' and 'peer disconnect' in the new version of the grpc api. 
_Describe the changes that were needed.
=> peer connect/disconnect

v2/concordium/service.proto, v2/concordium/types.proto
Expose `shutdown` in the new grpc api. 
_Describe the changes that were needed.
=> GRPC2 Shutdown

v2/concordium/health.proto
Add a new health check service to be used in automatic node issue detection.
=> Add a new service for checking the health of the node.

.github/docs.yaml
Add actions to render documentation.
=> Add job to generate docs.

v2/concordium/health.proto, v2/concordium/service.proto, v2/concordium/types.proto
added options for java code gen
```
option java_package = "com.concordium.grpc.v2";
option java_multiple_files = true;
```
=> Added options for JAVA code gen

v2/concordium/health.proto, v2/concordium/service.proto, v2/concordium/types.proto
=> Add namespace for C# projects.

v2/concordium/service.proto, v2/concordium/types.proto
Introduced `GetBakersRewardPeriod` api endpoint and the `BakerRewardPeriodInfo` which is the streamed response(s).
=> GetBakersRewardPeriod endpoint.

CHANGELOG.md
=> Add new endpoint to changelog.

CHANGELOG.md, v2/concordium/service.proto
Add GetBakerEarliestWinTime query endpoint.
- Add GetBakerEarliestWinTime.
=> Add GetBakerEarliestWinTime endpoint

v2/concordium/health.proto, v2/concordium/service.proto, v2/concordium/types.proto
Add `option go_package` for use when compiling for the go-sdk
Added `option go_package`
=> Added package option for generated go code

v2/concordium/types.proto
Push changes to fix review comments missed in #52.
- Documentation
=> Address review comments

CHANGELOG.md
7.0 release of the GRPC API.
- Update changelog.
=> Update changelog for release.

v2/concordium/types.proto
Fix: Chain parameter version 3 was missing from the chain parameter variant.
See purpose.
=> Missing chain parameter version

CHANGELOG.md, v2/concordium/types.proto
Update changelog to reflect changes to `BlockSpecialEvent`.
=> Document changes to `BlockSpecialEvent` in CHANGELOG.md.

README.md
Updated gRPC API with additional instructions and information for protoc and compilation.
Missing instructions and detail to support developers in utilizing the gRPC API repo.
Added instructions and information for protoc and compilation.
=> Update README.md with additional instructions for protoc and compilation

CHANGELOG.md
Release version for the Node 8.0 API.
- Bump changelog version.
=> Node 8.0 API release

CHANGELOG.md, v2/concordium/types.proto
To add protocol protocol 9. 
- Extend `ProtocolVersion` enum with a protocol version 9 variant `PROTOCOL_VERSION_9`.
=> Add protocol version 9.

CHANGELOG.md, v2/concordium/service.proto
This adds a `GetTokenList` endpoint returning the list of `TokenId`s existing at the end of the given block.
=> plt: add GetTokenList service endpoint

v2/concordium/types.proto
Introduce types related to token holder transactions.
Related PR for base: https://github.com/Concordium/concordium-base/pull/621
Related PR for node: https://github.com/Concordium/concordium-node/pull/1368
- Extend reject reasons with case for transactions with non-existent token IDs.
- Extend TransactionType enum with value representing token holder transactions.
=> Types related to token holder transaction (ref NOD-697)

CHANGELOG.md, v2/concordium/types.proto
Ref COR-1344.
Related PR for base https://github.com/Concordium/concordium-base/pull/625
Related PR for node: https://github.com/Concordium/concordium-node/pull/1376
=> Extend NextUpdateSequenceNumber for protocol level tokens

v2/concordium/protocol-level-tokens.proto
=> Replace token_symbol with token_id

.github/workflows/docs.yaml
Fix the documentation deployment to include the new protobuf files.
=> Include new files in documentation build.
